rm -f .github/workflows/tests.yml

mkdir -p .github/workflows
cat > .github/workflows/tests.yml <<'YML'
name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DIR_TESTS: /tmp/tests-bad-server
      REP_TESTS: https://github.com/Yandex-Practicum/tests-bad-server.git
      REPO: ${{ github.event.repository.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get testing lib
        run: git clone --depth 1 "$REP_TESTS" "$DIR_TESTS"

      - name: Start project
        run: bash "$DIR_TESTS/bin/start_project.sh"

      - name: Run tests
        run: bash "$DIR_TESTS/bin/run.sh"
YML

sed -i 's/\r$//' .github/workflows/tests.yml

git add .github/workflows/tests.yml
git commit -m "fix(ci): valid YAML tests workflow (LF, spaces only)"
git push
