name: Tests

on:
  push:
    branches: ['**']
    tags: ['**']

env:
  DIR_TESTS: /tmp/tests-bad-server
  REP_TESTS: https://github.com/Yandex-Practicum/tests-bad-server.git
  REPO: ${{ github.event.repository.name }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install helpers
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Clone tests repo
        run: git clone --depth 1 "$REP_TESTS" "$DIR_TESTS"

      - name: Start project (from tests repo script)
        run: bash "$DIR_TESTS/bin/start_project.sh"

      - name: Rebuild backend & server without cache and restart
        run: |
          docker compose build --no-cache server backend
          docker compose up -d server backend

      - name: Wait for services (nginx -> backend)
        run: |
          for i in $(seq 1 60); do
            curl -sf http://localhost:3000/health >/dev/null && break
            sleep 1
          done
          for i in $(seq 1 60); do
            curl -sf http://localhost:3000/api/health >/dev/null && break
            sleep 1
          done

      - name: Print nginx & env (diagnostics)
        run: |
          docker compose exec -T server nginx -T | sed -n '1,220p'
          docker compose exec -T backend node -e "console.log('UPLOAD_PATH=',process.env.UPLOAD_PATH,' CORS_ORIGINS=',process.env.CORS_ORIGINS)"

      - name: Smoke checks
        run: |
          set -e
          BASE=http://localhost:3000

          code=$(curl -s -o /dev/null -w '%{http_code}' "$BASE/orders?limit=5")
          test "$code" = "401"

          printf '\x89PNG\r\n\x1a\n\x00' > ok.png
          code=$(curl -s -o /dev/null -w '%{http_code}' -F "file=@ok.png" $BASE/api/upload)
          test "$code" = "201"

          echo 'not an image' > fake.png
          code=$(curl -s -o /dev/null -w '%{http_code}' -F "file=@fake.png" $BASE/api/upload)
          test "$code" = "400"

          node - <<'JS'
          const fs=require('fs');
          // маленький валидный PNG-заголовок + мусор
          const src=Buffer.concat([Buffer.from([0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A]), Buffer.alloc(16)]);
          // вставляем tEXt-чанк "hello=world"
          const out=Buffer.concat([src.slice(0,8), Buffer.from([0,0,0,11]), Buffer.from('tEXt'), Buffer.from('hello=world'), Buffer.alloc(4), src.slice(8)]);
          fs.writeFileSync('ok_meta.png', out);
          JS
          code=$(curl -s -o /dev/null -w '%{http_code}' -F "file=@ok_meta.png" $BASE/api/upload)
          test "$code" = "400"

      - name: Run tests (from tests repo)
        run: bash "$DIR_TESTS/bin/run.sh"
